# Generated by Django 3.2.5 on 2023-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercise',
            old_name='last_attempted',
            new_name='last_attempt',
        ),
    ]
