# Generated by Django 3.2.5 on 2023-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0002_exercisehistory_goal_userdetails_userexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('FAT_LOSS', 'Fat Loss'), ('MUSCLE_BUILDING', 'Muscle Building'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexibility')], max_length=50, unique=True),
        ),
    ]
