# Generated by Django 3.2.5 on 2023-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0002_rename_last_attempted_userexercise_last_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='last_attempt',
        ),
    ]
