# Generated by Django 3.2.5 on 2023-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0003_remove_userexercise_last_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='last_attempt',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
