# Generated by Django 3.2.5 on 2023-07-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0004_alter_goal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('sleep', models.FloatField(blank=True)),
                ('walk', models.FloatField(blank=True, null=True)),
                ('exercises', models.ManyToManyField(related_name='user_detail', to='fitness_track.UserExercise')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='complete_details',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
