# Generated by Django 3.2.5 on 2023-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0004_userexercise_last_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='last_attempt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
