# Generated by Django 3.2.5 on 2023-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0005_auto_20230716_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='focus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
