# Generated by Django 3.2.5 on 2023-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0006_auto_20230719_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='goals',
            field=models.ManyToManyField(related_name='user_detail', to='fitness_track.Goal'),
        ),
    ]
