# Generated by Django 3.2.5 on 2023-07-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0006_userexercise_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='exercises',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_exercise', to='fitness_track.customuser'),
            preserve_default=False,
        ),
    ]
