# Generated by Django 3.2.5 on 2023-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0007_userdetail_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='complete_details',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
