# Generated by Django 3.2.5 on 2023-07-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_track', '0009_auto_20230720_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
